package Database;
// Generated Sep 22, 2020 7:07:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String bookCode;
     private BookCategory bookCategory;
     private Member member;
     private String name;
     private String author;
     private Boolean status;
     private Set memberHasBooks = new HashSet(0);

    public Book() {
    }

	
    public Book(String bookCode, BookCategory bookCategory, Member member) {
        this.bookCode = bookCode;
        this.bookCategory = bookCategory;
        this.member = member;
    }
    public Book(String bookCode, BookCategory bookCategory, Member member, String name, String author, Boolean status, Set memberHasBooks) {
       this.bookCode = bookCode;
       this.bookCategory = bookCategory;
       this.member = member;
       this.name = name;
       this.author = author;
       this.status = status;
       this.memberHasBooks = memberHasBooks;
    }
   
    public String getBookCode() {
        return this.bookCode;
    }
    
    public void setBookCode(String bookCode) {
        this.bookCode = bookCode;
    }
    public BookCategory getBookCategory() {
        return this.bookCategory;
    }
    
    public void setBookCategory(BookCategory bookCategory) {
        this.bookCategory = bookCategory;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set getMemberHasBooks() {
        return this.memberHasBooks;
    }
    
    public void setMemberHasBooks(Set memberHasBooks) {
        this.memberHasBooks = memberHasBooks;
    }




}


