package Database;
// Generated Sep 22, 2020 7:07:07 PM by Hibernate Tools 4.3.1



/**
 * MemberHasBook generated by hbm2java
 */
public class MemberHasBook  implements java.io.Serializable {


     private Integer id;
     private Book book;
     private Member member;
     private Staff staff;
     private String dateIssue;
     private String dateReturn;
     private Boolean isReurned;

    public MemberHasBook() {
    }

	
    public MemberHasBook(Book book, Member member, Staff staff) {
        this.book = book;
        this.member = member;
        this.staff = staff;
    }
    public MemberHasBook(Book book, Member member, Staff staff, String dateIssue, String dateReturn, Boolean isReurned) {
       this.book = book;
       this.member = member;
       this.staff = staff;
       this.dateIssue = dateIssue;
       this.dateReturn = dateReturn;
       this.isReurned = isReurned;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public String getDateIssue() {
        return this.dateIssue;
    }
    
    public void setDateIssue(String dateIssue) {
        this.dateIssue = dateIssue;
    }
    public String getDateReturn() {
        return this.dateReturn;
    }
    
    public void setDateReturn(String dateReturn) {
        this.dateReturn = dateReturn;
    }
    public Boolean getIsReurned() {
        return this.isReurned;
    }
    
    public void setIsReurned(Boolean isReurned) {
        this.isReurned = isReurned;
    }




}


