package Database;
// Generated Sep 22, 2020 7:07:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String nic;
     private String mobile;
     private String email;
     private String gender;
     private String dateJoin;
     private String image;
     private Set books = new HashSet(0);
     private Set memberHasBooks = new HashSet(0);

    public Member() {
    }

    public Member(String fname, String lname, String nic, String mobile, String email, String gender, String dateJoin, String image, Set books, Set memberHasBooks) {
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.mobile = mobile;
       this.email = email;
       this.gender = gender;
       this.dateJoin = dateJoin;
       this.image = image;
       this.books = books;
       this.memberHasBooks = memberHasBooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDateJoin() {
        return this.dateJoin;
    }
    
    public void setDateJoin(String dateJoin) {
        this.dateJoin = dateJoin;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getBooks() {
        return this.books;
    }
    
    public void setBooks(Set books) {
        this.books = books;
    }
    public Set getMemberHasBooks() {
        return this.memberHasBooks;
    }
    
    public void setMemberHasBooks(Set memberHasBooks) {
        this.memberHasBooks = memberHasBooks;
    }




}


