package Database;
// Generated Sep 22, 2020 7:07:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private Integer id;
     private String fname;
     private String lname;
     private String nic;
     private String email;
     private String mobile;
     private String gender;
     private String bday;
     private String image;
     private String password;
     private Set memberHasBooks = new HashSet(0);

    public Staff() {
    }

    public Staff(String fname, String lname, String nic, String email, String mobile, String gender, String bday, String image, String password, Set memberHasBooks) {
       this.fname = fname;
       this.lname = lname;
       this.nic = nic;
       this.email = email;
       this.mobile = mobile;
       this.gender = gender;
       this.bday = bday;
       this.image = image;
       this.password = password;
       this.memberHasBooks = memberHasBooks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getBday() {
        return this.bday;
    }
    
    public void setBday(String bday) {
        this.bday = bday;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getMemberHasBooks() {
        return this.memberHasBooks;
    }
    
    public void setMemberHasBooks(Set memberHasBooks) {
        this.memberHasBooks = memberHasBooks;
    }




}


